//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class İzinTipi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public İzinTipi()
        {
            this.IzinTalebi = new HashSet<IzinTalebi>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage ="İzin Türü Alanı Boş geçilemez")]
        public string Tip { get; set; }

        [Required(ErrorMessage = "Gün Alanı Boş geçilemez")]
        public Nullable<int> Gun { get; set; }

        [Required(ErrorMessage = "Saat Alanı Boş geçilemez")]
        public Nullable<System.TimeSpan> Saat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinTalebi> IzinTalebi { get; set; }
    }
}
