//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnaylananIzin
    {
        public int Id { get; set; }
        public Nullable<int> IzinTalepId { get; set; }
        public Nullable<int> Personeld { get; set; }
    
        public virtual IzinTalebi IzinTalebi { get; set; }
    }
}
