//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzinSistemi.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personel()
        {
            this.IzinTalebi = new HashSet<IzinTalebi>();
        }
    
        public int PId { get; set; }
        public string Isim { get; set; }
        public string Soyisim { get; set; }
        public string KullanıcıAdı { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public Nullable<int> ToplamIzin { get; set; }
        public Nullable<int> KullanılanIzin { get; set; }
        public Nullable<int> KalanIzin { get; set; }
        public string Fotograf { get; set; }
        public string Sifre { get; set; }
        public string Yetki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IzinTalebi> IzinTalebi { get; set; }
    }
}
